In [1]:
import numpy as np
import pandas as pd

dataset = pd.read_csv("Fish.csv", delimiter='\t')

In [1]:
import tensorflow

In [3]:
print(tensorflow.__version__)

2.4.1


In [2]:
dataset

Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [3]:
dataset.isnull().any()

Species    False
Weight     False
Length1    False
Length2    False
Length3    False
Height     False
Width      False
dtype: bool

In [4]:
x = dataset.iloc[:,1:].values
y = dataset.iloc[:,0:1].values

In [5]:
dataset["Species"].unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct=ColumnTransformer([("one", OneHotEncoder(), [0])], remainder="passthrough")

In [7]:
y=ct.fit_transform(y)

In [8]:
y.shape

(159, 7)

<159x7 sparse matrix of type '<class 'numpy.float64'>'
	with 159 stored elements in Compressed Sparse Row format>

In [10]:
y=y.toarray()

In [12]:
y

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test= train_test_split(x,y,test_size=0.2,random_state=0)

In [14]:
x_train.shape

(127, 6)

In [15]:
y_train.shape

(127, 7)

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [17]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 

categorical=Sequential()
categorical.add(Dense( units= 6, kernel_initializer= "random_uniform", activation="relu"))

In [18]:
categorical.add(Dense( units= 12, kernel_initializer= "random_uniform", activation="relu"))
categorical.add(Dense( units= 12, kernel_initializer= "random_uniform", activation="relu"))
categorical.add(Dense( units= 12, kernel_initializer= "random_uniform", activation="relu"))

In [19]:
categorical.add(Dense( units= 7, kernel_initializer= "random_uniform", activation="softmax"))

In [20]:
categorical.compile(optimizer="rmsprop", loss="categorical_crossentropy", metrics=["accuracy"])

In [21]:
categorical.fit(x_train,y_train, epochs=350)

Epoch 1/350
4/4 [==============================] - 11s 41ms/step - loss: 1.9449 - accuracy: 0.2593
Epoch 2/350
4/4 [==============================] - 0s 14ms/step - loss: 1.9394 - accuracy: 0.3897
Epoch 3/350
4/4 [==============================] - ETA: 0s - loss: 1.9398 - accuracy: 0.25 - 0s 8ms/step - loss: 1.9368 - accuracy: 0.3397
Epoch 4/350
4/4 [==============================] - 0s 15ms/step - loss: 1.9327 - accuracy: 0.3678
Epoch 5/350
4/4 [==============================] - 0s 6ms/step - loss: 1.9299 - accuracy: 0.3668
Epoch 6/350
4/4 [==============================] - 0s 14ms/step - loss: 1.9249 - accuracy: 0.3709
Epoch 7/350
4/4 [==============================] - 0s 13ms/step - loss: 1.9224 - accuracy: 0.3866
Epoch 8/350
4/4 [==============================] - 0s 12ms/step - loss: 1.9202 - accuracy: 0.3407
Epoch 9/350
4/4 [==============================] - ETA: 0s - loss: 1.9023 - accuracy: 0.43 - 0s 14ms/step - loss: 1.9096 - accuracy: 0.3897
Epoch 10/350
4/4 [=================

4/4 [==============================] - 0s 5ms/step - loss: 1.4377 - accuracy: 0.4859
Epoch 165/350
4/4 [==============================] - 0s 5ms/step - loss: 1.4123 - accuracy: 0.4859
Epoch 166/350
4/4 [==============================] - 0s 3ms/step - loss: 1.3340 - accuracy: 0.4849
Epoch 167/350
4/4 [==============================] - 0s 3ms/step - loss: 1.3852 - accuracy: 0.5016
Epoch 168/350
4/4 [==============================] - 0s 3ms/step - loss: 1.3977 - accuracy: 0.5151
Epoch 169/350
4/4 [==============================] - 0s 5ms/step - loss: 1.4172 - accuracy: 0.5037
Epoch 170/350
4/4 [==============================] - 0s 5ms/step - loss: 1.3297 - accuracy: 0.5120
Epoch 171/350
4/4 [==============================] - 0s 3ms/step - loss: 1.3315 - accuracy: 0.5224
Epoch 172/350
4/4 [==============================] - 0s 3ms/step - loss: 1.3953 - accuracy: 0.4787
Epoch 173/350
4/4 [==============================] - 0s 3ms/step - loss: 1.3565 - accuracy: 0.5016
Epoch 174/350
4/4 [=====

4/4 [==============================] - 0s 3ms/step - loss: 0.8405 - accuracy: 0.7032
Epoch 329/350
4/4 [==============================] - 0s 3ms/step - loss: 0.9095 - accuracy: 0.6625
Epoch 330/350
4/4 [==============================] - 0s 3ms/step - loss: 0.9052 - accuracy: 0.6938
Epoch 331/350
4/4 [==============================] - 0s 3ms/step - loss: 0.8772 - accuracy: 0.6896
Epoch 332/350
4/4 [==============================] - 0s 3ms/step - loss: 0.8769 - accuracy: 0.6876
Epoch 333/350
4/4 [==============================] - 0s 3ms/step - loss: 0.8842 - accuracy: 0.6782
Epoch 334/350
4/4 [==============================] - 0s 3ms/step - loss: 0.8799 - accuracy: 0.6771
Epoch 335/350
4/4 [==============================] - 0s 3ms/step - loss: 0.8975 - accuracy: 0.6740
Epoch 336/350
4/4 [==============================] - 0s 3ms/step - loss: 0.8728 - accuracy: 0.6886
Epoch 337/350
4/4 [==============================] - 0s 3ms/step - loss: 0.8836 - accuracy: 0.6657
Epoch 338/350
4/4 [=====

In [26]:
x_test

array([[ 0.03079721,  0.19914534,  0.21275144,  0.39401436,  0.86816042,
         0.20902029],
       [-1.14637952, -0.70075761, -0.7139078 , -0.6978938 , -0.54931349,
        -0.59608381],
       [-0.63325121, -0.43915791, -0.42127857, -0.50099233, -0.5951226 ,
        -0.37146795],
       [-0.66343522, -0.54379779, -0.51882164, -0.47414212, -0.42158799,
        -0.31414098],
       [ 0.53185192,  0.65956081,  0.65169528,  0.52826536,  0.31591123,
         1.2301382 ],
       [ 1.57018216,  1.1827602 ,  1.18818221,  1.06526938,  0.65307269,
         1.7339298 ],
       [ 1.26834197,  0.8374486 ,  0.83702713,  0.80571744,  0.66021177,
         1.3420852 ],
       [-0.24085896,  0.95255247,  0.9248159 ,  0.82361757, -0.59205646,
        -0.1941333 ],
       [ 1.7965623 ,  1.22461615,  1.28572528,  1.36957165,  2.23314378,
         1.44657309],
       [-0.79926331, -0.70075761, -0.66513626, -0.724744  , -0.67692458,
        -0.62261182],
       [-0.54269915,  0.45028105,  0.43710051,  0.

In [22]:
ypred = categorical.predict(x_test)
ypred

array([[8.17282259e-01, 1.49141580e-01, 3.34626287e-02, 1.31728118e-15,
        4.92763149e-07, 3.25181573e-17, 1.13157170e-04],
       [4.20204923e-02, 9.39393118e-02, 7.00959325e-01, 9.14303400e-03,
        1.16548039e-01, 7.38951564e-03, 3.00002564e-02],
       [2.87101213e-02, 7.36191273e-02, 6.28744245e-01, 3.24877761e-02,
        1.72124028e-01, 2.99594160e-02, 3.43552567e-02],
       [2.28233635e-02, 6.30337819e-02, 5.65563142e-01, 5.78601100e-02,
        1.98375002e-01, 5.60228936e-02, 3.63217071e-02],
       [6.41062707e-02, 1.21567875e-01, 7.20583379e-01, 1.64712721e-03,
        6.49266094e-02, 1.05870957e-03, 2.61101034e-02],
       [7.26398826e-02, 1.30562246e-01, 7.17529058e-01, 9.36496654e-04,
        5.30908108e-02, 5.59109321e-04, 2.46823411e-02],
       [1.84909597e-01, 2.07169950e-01, 5.87913573e-01, 5.14182148e-06,
        7.47713074e-03, 1.58937053e-06, 1.25230346e-02],
       [4.13752161e-03, 1.55335404e-02, 1.66954070e-01, 2.90347308e-01,
        1.60407618e-01, 3

In [23]:
y_test

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
 

In [24]:
ypred[0]

array([8.1728226e-01, 1.4914158e-01, 3.3462629e-02, 1.3172812e-15,
       4.9276315e-07, 3.2518157e-17, 1.1315717e-04], dtype=float32)

In [25]:
categorical.save("Fish.h5")

In [28]:
import pickle
pickle.dump(sc,open('scaling.pkl','wb'))

In [5]:
from tensorflow.keras.models import load_model
model=load_model('fish.h5')

In [9]:
model.predict([[1,2,3,4,5,6]])

array([[9.9999678e-01, 3.1975517e-06, 4.7424532e-13, 0.0000000e+00,
        1.5973325e-37, 0.0000000e+00, 5.0670836e-22]], dtype=float32)