# 50 Startups

### Importing Libraries

In [1]:
import numpy as np
import pandas as pd

dataset = pd.read_csv("50_Startups.csv")
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87              NaN  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08             NaN        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

### Handling Missing Values

In [2]:
dataset.isnull().any()

R&D Spend          False
Administration      True
Marketing Spend     True
State              False
Profit             False
dtype: bool

In [3]:
dataset["Administration"].mean()

121564.03816326526

In [4]:
dataset["Marketing Spend"].mean()

212725.26673469393

In [5]:
dataset["Administration"].fillna(dataset["Administration"].mean(), inplace=True)
dataset["Marketing Spend"].fillna(dataset["Marketing Spend"].mean(), inplace=True)

In [6]:
dataset.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool

In [7]:
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20   136897.800000    471784.100000    New York  192261.83
1   162597.70   151377.590000    443898.530000  California  191792.06
2   153441.51   101145.550000    407934.540000     Florida  191050.39
3   144372.41   118671.850000    383199.620000    New York  182901.99
4   142107.34    91391.770000    366168.420000     Florida  166187.94
5   131876.90    99814.710000    362861.360000    New York  156991.12
6   134615.46   147198.870000    212725.266735  California  156122.51
7   130298.13   145530.060000    323876.680000     Florida  155752.60
8   120542.52   148718.950000    311613.290000    New York  152211.77
9   123334.88   108679.170000    304981.620000  California  149759.96
10  101913.08   121564.038163    229160.950000     Florida  146121.95
11  100671.96    91790.610000    249744.550000  California  144259.40
12   93863.75   127320.380000    249839.440000     Florida  141585.52
13   91992.39   135495.070000    252664.930000  California  134307.35
14  119943.24   156547.420000    256512.920000     Florida  132602.65
15  114523.61   122616.840000    261776.230000    New York  129917.04
16   78013.11   121597.550000    264346.060000  California  126992.93
17   94657.16   145077.580000    282574.310000    New York  125370.37
18   91749.16   114175.790000    294919.570000     Florida  124266.90
19   86419.70   153514.110000         0.000000    New York  122776.86
20   76253.86   113867.300000    298664.470000  California  118474.03
21   78389.47   153773.430000    299737.290000    New York  111313.02
22   73994.56   122782.750000    303319.260000     Florida  110352.25
23   67532.53   105751.030000    304768.730000     Florida  108733.99
24   77044.01    99281.340000    140574.810000    New York  108552.04
25   64664.71   139553.160000    137962.620000  California  107404.34
26   75328.87   144135.980000    134050.070000     Florida  105733.54
27   72107.60   127864.550000    353183.810000    New York  105008.31
28   66051.52   182645.560000    118148.200000     Florida  103282.38
29   65605.48   153032.060000    107138.380000    New York  101004.64
30   61994.48   115641.280000     91131.240000     Florida   99937.59
31   61136.38   152701.920000     88218.230000    New York   97483.56
32   63408.86   129219.610000     46085.250000  California   97427.84
33   55493.95   103057.490000    214634.810000     Florida   96778.92
34   46426.07   157693.920000    210797.670000  California   96712.80
35   46014.02    85047.440000    205517.640000    New York   96479.51
36   28663.76   127056.210000    201126.820000     Florida   90708.19
37   44069.95    51283.140000    197029.420000  California   89949.14
38   20229.59    65947.930000    185265.100000    New York   81229.06
39   38558.51    82982.090000    174999.300000  California   81005.76
40   28754.33   118546.050000    172795.670000  California   78239.91
41   27892.92    84710.770000    164470.710000     Florida   77798.83
42   23640.93    96189.630000    148001.110000  California   71498.49
43   15505.73   127382.300000     35534.170000    New York   69758.98
44   22177.74   154806.140000     28334.720000  California   65200.33
45    1000.23   124153.040000      1903.930000    New York   64926.08
46    1315.46   115816.210000    297114.460000     Florida   49490.75
47       0.00   135426.920000         0.000000  California   42559.73
48     542.05    51743.150000         0.000000    New York   35673.41
49       0.00   116983.800000     45173.060000  California   14681.40

### Splitting data into x and y

In [8]:
x = dataset.iloc[:,:4].values
y = dataset.iloc[:,4:5].values

In [9]:
x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 212725.26673469393, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 121564.03816326526, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16

In [10]:
y

array([[192261.83],
       [191792.06],
       [191050.39],
       [182901.99],
       [166187.94],
       [156991.12],
       [156122.51],
       [155752.6 ],
       [152211.77],
       [149759.96],
       [146121.95],
       [144259.4 ],
       [141585.52],
       [134307.35],
       [132602.65],
       [129917.04],
       [126992.93],
       [125370.37],
       [124266.9 ],
       [122776.86],
       [118474.03],
       [111313.02],
       [110352.25],
       [108733.99],
       [108552.04],
       [107404.34],
       [105733.54],
       [105008.31],
       [103282.38],
       [101004.64],
       [ 99937.59],
       [ 97483.56],
       [ 97427.84],
       [ 96778.92],
       [ 96712.8 ],
       [ 96479.51],
       [ 90708.19],
       [ 89949.14],
       [ 81229.06],
       [ 81005.76],
       [ 78239.91],
       [ 77798.83],
       [ 71498.49],
       [ 69758.98],
       [ 65200.33],
       [ 64926.08],
       [ 49490.75],
       [ 42559.73],
       [ 35673.41],
       [ 14681.4 ]])

### Handling Categorical Data

In [11]:
dataset["State"].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [12]:
# Arrangement: California, Florida, New York
x.shape

(50, 4)

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct=ColumnTransformer([("one", OneHotEncoder(), [3])], remainder="passthrough")
x=ct.fit_transform(x)

In [14]:
x.shape

(50, 6)

In [15]:
y.shape

(50, 1)

In [16]:
x[0]

array([0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1], dtype=object)

In [17]:
x

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 212725.26673469393],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 121564.03816326526, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 9

In [18]:
dataset.head(10)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80    471784.100000    New York  192261.83
1  162597.70       151377.59    443898.530000  California  191792.06
2  153441.51       101145.55    407934.540000     Florida  191050.39
3  144372.41       118671.85    383199.620000    New York  182901.99
4  142107.34        91391.77    366168.420000     Florida  166187.94
5  131876.90        99814.71    362861.360000    New York  156991.12
6  134615.46       147198.87    212725.266735  California  156122.51
7  130298.13       145530.06    323876.680000     Florida  155752.60
8  120542.52       148718.95    311613.290000    New York  152211.77
9  123334.88       108679.17    304981.620000  California  149759.96

### Splitting the data to train and test

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test= train_test_split(x,y,test_size=0.2,random_state=0)

In [20]:
print("x_train shape", "\t", x_train.shape)
print("x_test shape", "\t", x_test.shape)
print("y_train shape", "\t", y_train.shape)
print("y_test shape", "\t", y_test.shape)
print("x shape", "\t", x.shape)
print("y shape", "\t", y.shape)

x_train shape 	 (40, 6)
x_test shape 	 (10, 6)
y_train shape 	 (40, 1)
y_test shape 	 (10, 1)
x shape 	 (50, 6)
y shape 	 (50, 1)


### Feature Scaling

In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

### Model Building

In [22]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 

In [23]:
regression = Sequential()

In [24]:
x.shape

(50, 6)

##### Adding Input Layer

In [25]:
regression.add(Dense( units=6 , kernel_initializer= "random_uniform", activation="relu"))

##### Adding Hidden Layer

In [26]:
regression.add(Dense( units= 12, kernel_initializer= "random_uniform", activation="relu"))

##### Adding Output Layer

In [27]:
regression.add(Dense( units= 1, kernel_initializer= "random_uniform", activation="relu"))

##### Compile Data

In [28]:
regression.compile(optimizer = "adam", loss = "mse", metrics=['mse']) 

##### Fit Model

In [29]:
regression.fit(x_train,y_train, epochs=500)

Train on 40 samples
Epoch 1/500
40/40 [==============================] - 0s 4ms/sample - loss: 13615995289.6000 - mse: 13615994880.0000
Epoch 2/500
40/40 [==============================] - 0s 73us/sample - loss: 13615995699.2000 - mse: 13615994880.0000
Epoch 3/500
40/40 [==============================] - 0s 74us/sample - loss: 13615994470.4000 - mse: 13615994880.0000
Epoch 4/500
40/40 [==============================] - 0s 100us/sample - loss: 13615994470.4000 - mse: 13615994880.0000
Epoch 5/500
40/40 [==============================] - 0s 75us/sample - loss: 13615993651.2000 - mse: 13615993856.0000
Epoch 6/500
40/40 [==============================] - 0s 51us/sample - loss: 13615992832.0000 - mse: 13615992832.0000
Epoch 7/500
40/40 [==============================] - 0s 50us/sample - loss: 13615991603.2000 - mse: 13615991808.0000
Epoch 8/500
40/40 [==============================] - 0s 75us/sample - loss: 13615992012.8000 - mse: 13615991808.0000
Epoch 9/500
40/40 [=========================

40/40 [==============================] - 0s 75us/sample - loss: 13615735193.6000 - mse: 13615734784.0000
Epoch 71/500
40/40 [==============================] - 0s 51us/sample - loss: 13615723315.2000 - mse: 13615723520.0000
Epoch 72/500
40/40 [==============================] - 0s 49us/sample - loss: 13615711846.4000 - mse: 13615712256.0000
Epoch 73/500
40/40 [==============================] - 0s 75us/sample - loss: 13615699148.8000 - mse: 13615698944.0000
Epoch 74/500
40/40 [==============================] - 0s 50us/sample - loss: 13615686860.8000 - mse: 13615687680.0000
Epoch 75/500
40/40 [==============================] - 0s 75us/sample - loss: 13615673958.4000 - mse: 13615674368.0000
Epoch 76/500
40/40 [==============================] - 0s 74us/sample - loss: 13615660032.0000 - mse: 13615660032.0000
Epoch 77/500
40/40 [==============================] - 0s 76us/sample - loss: 13615645081.6000 - mse: 13615644672.0000
Epoch 78/500
40/40 [==============================] - 0s 50us/sample 

40/40 [==============================] - 0s 50us/sample - loss: 13613620838.4000 - mse: 13613621248.0000
Epoch 140/500
40/40 [==============================] - 0s 75us/sample - loss: 13613569228.8000 - mse: 13613569024.0000
Epoch 141/500
40/40 [==============================] - 0s 50us/sample - loss: 13613509632.0000 - mse: 13613509632.0000
Epoch 142/500
40/40 [==============================] - 0s 74us/sample - loss: 13613448806.4000 - mse: 13613449216.0000
Epoch 143/500
40/40 [==============================] - 0s 75us/sample - loss: 13613391872.0000 - mse: 13613391872.0000
Epoch 144/500
40/40 [==============================] - 0s 75us/sample - loss: 13613332070.4000 - mse: 13613332480.0000
Epoch 145/500
40/40 [==============================] - 0s 75us/sample - loss: 13613268172.8000 - mse: 13613267968.0000
Epoch 146/500
40/40 [==============================] - 0s 50us/sample - loss: 13613208371.2000 - mse: 13613208576.0000
Epoch 147/500
40/40 [==============================] - 0s 50us

Epoch 208/500
40/40 [==============================] - 0s 50us/sample - loss: 13607322419.2000 - mse: 13607322624.0000
Epoch 209/500
40/40 [==============================] - 0s 75us/sample - loss: 13607186022.4000 - mse: 13607185408.0000
Epoch 210/500
40/40 [==============================] - 0s 49us/sample - loss: 13607045529.6000 - mse: 13607045120.0000
Epoch 211/500
40/40 [==============================] - 0s 74us/sample - loss: 13606912409.6000 - mse: 13606912000.0000
Epoch 212/500
40/40 [==============================] - 0s 50us/sample - loss: 13606776832.0000 - mse: 13606776832.0000
Epoch 213/500
40/40 [==============================] - 0s 50us/sample - loss: 13606635520.0000 - mse: 13606635520.0000
Epoch 214/500
40/40 [==============================] - 0s 50us/sample - loss: 13606503833.6000 - mse: 13606504448.0000
Epoch 215/500
40/40 [==============================] - 0s 75us/sample - loss: 13606362726.4000 - mse: 13606363136.0000
Epoch 216/500
40/40 [===========================

40/40 [==============================] - 0s 49us/sample - loss: 13595083366.4000 - mse: 13595083776.0000
Epoch 277/500
40/40 [==============================] - 0s 50us/sample - loss: 13594840678.4000 - mse: 13594840064.0000
Epoch 278/500
40/40 [==============================] - 0s 75us/sample - loss: 13594618675.2000 - mse: 13594618880.0000
Epoch 279/500
40/40 [==============================] - 0s 75us/sample - loss: 13594386432.0000 - mse: 13594386432.0000
Epoch 280/500
40/40 [==============================] - 0s 75us/sample - loss: 13594143948.8000 - mse: 13594143744.0000
Epoch 281/500
40/40 [==============================] - 0s 75us/sample - loss: 13593911296.0000 - mse: 13593911296.0000
Epoch 282/500
40/40 [==============================] - 0s 50us/sample - loss: 13593681510.4000 - mse: 13593681920.0000
Epoch 283/500
40/40 [==============================] - 0s 75us/sample - loss: 13593441894.4000 - mse: 13593442304.0000
Epoch 284/500
40/40 [==============================] - 0s 61us

Epoch 345/500
40/40 [==============================] - 0s 51us/sample - loss: 13574815744.0000 - mse: 13574815744.0000
Epoch 346/500
40/40 [==============================] - 0s 49us/sample - loss: 13574416998.4000 - mse: 13574416384.0000
Epoch 347/500
40/40 [==============================] - 0s 51us/sample - loss: 13574042419.2000 - mse: 13574042624.0000
Epoch 348/500
40/40 [==============================] - 0s 75us/sample - loss: 13573672140.8000 - mse: 13573671936.0000
Epoch 349/500
40/40 [==============================] - 0s 50us/sample - loss: 13573287731.2000 - mse: 13573287936.0000
Epoch 350/500
40/40 [==============================] - 0s 75us/sample - loss: 13572926668.8000 - mse: 13572926464.0000
Epoch 351/500
40/40 [==============================] - 0s 50us/sample - loss: 13572548198.4000 - mse: 13572548608.0000
Epoch 352/500
40/40 [==============================] - 0s 75us/sample - loss: 13572184064.0000 - mse: 13572184064.0000
Epoch 353/500
40/40 [===========================

40/40 [==============================] - 0s 49us/sample - loss: 13545771008.0000 - mse: 13545771008.0000
Epoch 414/500
40/40 [==============================] - 0s 50us/sample - loss: 13545229516.8000 - mse: 13545229312.0000
Epoch 415/500
40/40 [==============================] - 0s 49us/sample - loss: 13544762982.4000 - mse: 13544762368.0000
Epoch 416/500
40/40 [==============================] - 0s 50us/sample - loss: 13544249139.2000 - mse: 13544249344.0000
Epoch 417/500
40/40 [==============================] - 0s 74us/sample - loss: 13543743078.4000 - mse: 13543743488.0000
Epoch 418/500
40/40 [==============================] - 0s 74us/sample - loss: 13543201996.8000 - mse: 13543201792.0000
Epoch 419/500
40/40 [==============================] - 0s 50us/sample - loss: 13542723379.2000 - mse: 13542723584.0000
Epoch 420/500
40/40 [==============================] - 0s 74us/sample - loss: 13542194585.6000 - mse: 13542194176.0000
Epoch 421/500
40/40 [==============================] - 0s 75us

Epoch 482/500
40/40 [==============================] - 0s 50us/sample - loss: 13505162444.8000 - mse: 13505162240.0000
Epoch 483/500
40/40 [==============================] - 0s 49us/sample - loss: 13504454246.4000 - mse: 13504454656.0000
Epoch 484/500
40/40 [==============================] - 0s 51us/sample - loss: 13503818956.8000 - mse: 13503818752.0000
Epoch 485/500
40/40 [==============================] - 0s 50us/sample - loss: 13503093555.2000 - mse: 13503092736.0000
Epoch 486/500
40/40 [==============================] - 0s 49us/sample - loss: 13502448025.6000 - mse: 13502447616.0000
Epoch 487/500
40/40 [==============================] - 0s 50us/sample - loss: 13501733683.2000 - mse: 13501732864.0000
Epoch 488/500
40/40 [==============================] - 0s 50us/sample - loss: 13501079961.6000 - mse: 13501079552.0000
Epoch 489/500
40/40 [==============================] - 0s 49us/sample - loss: 13500336537.6000 - mse: 13500336128.0000
Epoch 490/500
40/40 [===========================

In [30]:
ypred = regression.predict(x_test)

In [31]:
ypred

array([[482.30014 ],
       [329.4816  ],
       [411.79285 ],
       [140.84833 ],
       [763.2901  ],
       [668.9683  ],
       [ 21.914587],
       [380.76193 ],
       [418.37082 ],
       [569.7861  ]], dtype=float32)

In [32]:
y_test

array([[103282.38],
       [144259.4 ],
       [146121.95],
       [ 77798.83],
       [191050.39],
       [105008.31],
       [ 81229.06],
       [ 97483.56],
       [110352.25],
       [166187.94]])

In [33]:
ypred=ypred>0

In [34]:
ypred

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [35]:
dataset.head(1)

R&D Spend  Administration  Marketing Spend     State     Profit
0   165349.2        136897.8         471784.1  New York  192261.83

### Regression 

In [36]:
yp=regression.predict(sc.transform([[165349.2,136897.8,471784.1,0,0,1]]))

In [37]:
yp

array([[61251344.]], dtype=float32)