In [1]:
#Import libraries
import pandas as pd
import nltk
import re

In [2]:
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [3]:
#Read the Dataset
df=pd.read_csv('MovieData.csv')

ps=PorterStemmer()
data=[]

In [4]:
#Text Preprocessing

for i in range(0,1000):
  review=df['review'][i]

  #remove uneccessary things
  review=re.sub('[^a-zA-Z]',' ',review )

  #Lower case text
  review=review.lower()

  #split the text
  review=review.split()

  #Stemming & Remove Stopwords
  review=[ps.stem(word) for word in review if not word in 
          set(stopwords.words('english'))]

  review=' '.join(review)
  data.append(review)

In [5]:
import numpy as np

In [6]:
#Tokenization or Vectorization
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=3000)

In [7]:
x=cv.fit_transform(data).toarray()
y=df.iloc[:1000,1:2].values

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct=ColumnTransformer([("one", OneHotEncoder(), [0])], remainder="passthrough")
y=ct.fit_transform(y)

In [8]:
print(x.shape)
print(y.shape)

(1000, 3000)
(1000, 2)


In [9]:
x=np.asarray(x).astype(np.float32)
print(x)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [10]:
y=y[:,1:2]
y = np.asarray(y).astype(np.float32)
print(y)

[[1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [12]:
#ANN Layers
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
model=Sequential()

In [14]:
model.add(Dense(1565,activation='relu'))
model.add(Dense(3000,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(x_train,y_train,epochs=10)

Epoch 1/10
25/25 [==============================] - 3s 77ms/step - loss: 0.6112 - accuracy: 0.7075
Epoch 2/10
25/25 [==============================] - 2s 76ms/step - loss: 0.0654 - accuracy: 0.9850
Epoch 3/10
25/25 [==============================] - 2s 77ms/step - loss: 0.0057 - accuracy: 0.9987
Epoch 4/10
25/25 [==============================] - 2s 76ms/step - loss: 0.0013 - accuracy: 1.0000
Epoch 5/10
25/25 [==============================] - 2s 76ms/step - loss: 5.7028e-04 - accuracy: 1.0000
Epoch 6/10
25/25 [==============================] - 2s 76ms/step - loss: 3.5726e-04 - accuracy: 1.0000
Epoch 7/10
25/25 [==============================] - 2s 75ms/step - loss: 2.4457e-04 - accuracy: 1.0000
Epoch 8/10
25/25 [==============================] - 2s 77ms/step - loss: 1.7632e-04 - accuracy: 1.0000
Epoch 9/10
25/25 [==============================] - 2s 74ms/step - loss: 1.3224e-04 - accuracy: 1.0000
Epoch 10/10
25/25 [==============================] - 2s 76ms/step - loss: 1.0044e-04 - ac

In [15]:
#save the model
model.save('movies.h5')

In [16]:
text= "i love the the movie"
text=re.sub('[^a-zA-Z]',' ',text)
text=text.lower()
text=text.split()
text=[ps.stem(word) for word in text if not word in set(stopwords.words('english'))]
text=' '.join(text)

In [17]:
y_p1= model.predict(cv.transform([text]))
y_p1=y_p1>0.5
y_p1

array([[ True]])